os: linux
dist: trusty
language: generic
sudo: false
before_install:
  - sudo apt-get build-dep emacs24
  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - export PATH="${HOME}/.evm/bin:${HOME}/.cask/bin:$PATH"
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
env:
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26.1-travis
script:
  - emacs --version
  - make clean test -C tests
