[package]
name = "helm-rg"
version = "0.0.0"
edition = "2018"
authors = ["Danny McClanahan <dmcC2@hypnicjerk.ai>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
ascii = "1"
regex = "1"

[build-dependencies]
bindgen = "0.59"
